"""initial schema

Revision ID: dab26c86f09e
Revises: 
Create Date: 2026-03-22 16:59:17.574483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab26c86f09e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balances', sa.JSON(), nullable=False),
    sa.Column('debts', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('owed', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('net_position', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_audits_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_balance_audits_id'), ['id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('system_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metadata_id'), ['id'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wallet_type', sa.Enum('NORMAL', 'CREDIT', name='wallettype'), nullable=False),
    sa.Column('credit_limit', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallets_wallet_type'), ['wallet_type'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'year', 'month', name='uq_budget_category_month')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_year'), ['year'], unique=False)

    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_category_subcategory')
    )
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcategories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcategories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcategories_name'), ['name'], unique=False)

    op.create_table('wallet_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'snapshot_date', name='uq_wallet_snapshot_date')
    )
    with op.batch_alter_table('wallet_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_snapshots_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INFLOW', 'OUTFLOW', 'RESERVED', name='transactiondirection'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('classification', sa.Enum('EXPENSE', 'INCOME', 'LEND', 'BORROW', 'DEBT_COLLECTION', 'LOAN_REPAYMENT', 'SPLIT_PAYMENT', 'TRANSFER', 'INSTALLMENT', 'INSTALLMT_CHRGE', name='transactionclassification'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('paired_transaction_id', sa.Integer(), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=False, comment='If True, transaction is excluded from budget calculations'),
    sa.Column('is_calibration', sa.Boolean(), nullable=False, comment='If True, transaction is a wallet balance calibration'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['paired_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_calibration'), ['is_calibration'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_ignored'), ['is_ignored'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_subcategory_id'), ['subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('linked_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('SPLIT_PAYMENT', 'LOAN', 'DEBT', 'INSTALLMENT', name='linktype'), nullable=False),
    sa.Column('primary_transaction_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('user_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('pending_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'SETTLED', name='linkstatus'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linked_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linked_entries_counterparty_name'), ['counterparty_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_entries_link_type'), ['link_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_entries_primary_transaction_id'), ['primary_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_linked_entries_status'), ['status'], unique=False)

    op.create_table('linked_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_entry_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_entry_id'], ['linked_entries.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linked_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linked_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_transactions_linked_entry_id'), ['linked_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_transactions_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linked_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linked_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_linked_transactions_linked_entry_id'))
        batch_op.drop_index(batch_op.f('ix_linked_transactions_id'))

    op.drop_table('linked_transactions')
    with op.batch_alter_table('linked_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linked_entries_status'))
        batch_op.drop_index(batch_op.f('ix_linked_entries_primary_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_linked_entries_link_type'))
        batch_op.drop_index(batch_op.f('ix_linked_entries_id'))
        batch_op.drop_index(batch_op.f('ix_linked_entries_counterparty_name'))

    op.drop_table('linked_entries')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_subcategory_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_ignored'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_calibration'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_direction'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_classification'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('wallet_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_snapshots_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_wallet_snapshots_id'))

    op.drop_table('wallet_snapshots')
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcategories_name'))
        batch_op.drop_index(batch_op.f('ix_subcategories_id'))
        batch_op.drop_index(batch_op.f('ix_subcategories_category_id'))

    op.drop_table('subcategories')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_year'))
        batch_op.drop_index(batch_op.f('ix_budgets_month'))
        batch_op.drop_index(batch_op.f('ix_budgets_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_wallet_type'))
        batch_op.drop_index(batch_op.f('ix_wallets_name'))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('system_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metadata_id'))

    op.drop_table('system_metadata')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('balance_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_audits_id'))
        batch_op.drop_index(batch_op.f('ix_balance_audits_date'))

    op.drop_table('balance_audits')
    # ### end Alembic commands ###
